name: Hello World

on:
    workflow_dispatch:  
#    schedule:
#        - cron: "*/1 * * * *"

jobs:
    hello-jobs:
        timeout-minutes: 1
        runs-on: ubuntu-latest
        steps:
            - name: Echo text
              run: '''echo "Hello, world!"
                      sleep 100''' 

