name: Hello World

on: 
    schedule:
        - cron: "*/1 * * * *"

jobs:
    hello-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Echo text
              run: echo "Hello, world!" 

