name: Hello World

on:
    push:
    workflow_dispatch:  
#    schedule:
#        - cron: "*/1 * * * *"

jobs:
    deploy:
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-20.04]
                images: [hello-world, alpine]
        runs-on: ${{ matrix.os }}
        steps:
            - name: docker information
              run: docker info
            - name: run docker images on ${{ matrix.os }}
              run: docker run ${{ matrix.images }}
